

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Edit Manufacturer')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getBackUrl()?>'" class="scalable back" type="button"><span><?php echo $this->__('Back')?></span></button>
                <button onclick="document.getElementById('edit_form').submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form id="edit_form" name="edit_form" action="<?php echo $this->getUrl('*/*/Save')?>">
<input type="hidden" id="man_id" name="man_id" value="<?php echo $this->getManufacturer()->getId(); ?>">
<div class="entry-edit">
    
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">Id</td>
                    <td class="input-ele"><?php echo $this->getManufacturer()->getId(); ?></td>
                    <td rowspan="7" width="20">&nbsp;</td>
                    <td class="label"><?php echo $this->__('City')?></td>
                    <td class="input-ele"><input type="text" id="man_city" name="man_city" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_city(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Name')?></td>
                    <td class="input-ele"><input type="text" id="man_name" name="man_name" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_name(); ?>"></td>
                    <td class="label"><?php echo $this->__('Country')?></td>
                    <td class="input-ele"><?php echo $this->getCountryCombo('man_country', $this->getManufacturer()->getman_country()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Main Contact')?></td>
                    <td class="input-ele"><input type="text" id="man_contact" name="man_contact" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_contact(); ?>"></td>
                    <td class="label"><?php echo $this->__('Phone')?></td>
                    <td class="input-ele"><input type="text" id="man_tel" name="man_tel" value="<?php echo $this->getManufacturer()->getman_tel(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Address 1')?></td>
                    <td class="input-ele"><input type="text" id="man_address1" name="man_address1" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_address1(); ?>"></td>
                    <td class="label">Fax</td>
                    <td class="input-ele"><input type="text" id="man_fax" name="man_fax" value="<?php echo $this->getManufacturer()->getman_fax(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Address 2')?></td>
                    <td class="input-ele"><input type="text" id="man_address2" name="man_address2" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_address2(); ?>"></td>
                    <td class="label">Email</td>
                    <td class="input-ele"><input type="text" id="man_email" name="man_email" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_email(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Zip Code')?></td>
                    <td class="input-ele"><input type="text" id="man_zipcode" name="man_zipcode" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_zipcode(); ?>"></td>
                    <td class="label"><?php echo $this->__('Website')?></td>
                    <td class="input-ele"><input type="text" id="man_website" name="man_website" style="width:400px;" value="<?php echo $this->getManufacturer()->getman_website(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Comments')?></td>
                    <td class="input-ele"><textarea id="man_comments" name="man_comments" cols="75" rows="5"><?php echo $this->getManufacturer()->getman_comments(); ?></textarea></td>
                    <td class="label"><?php echo $this->__('Magento Manufacturer')?></td>
                    <td>
                    	<?php echo $this->getMagentoManufacturerListAsCombo('man_attribute_option_id', $this->getManufacturer()->getman_attribute_option_id()); ?>
                    	<input type="checkbox" id="create_magento_manufacturer" name="create_magento_manufacturer" value="1"> <?php echo $this->__('Create')?>
                    </td>
                </tr>
                <tr>
                	
                </tr>
            </table>
        </fieldset>
</div>

<script type="text/javascript">
    var editForm = new varienForm('new_form');
</script>

</form>

<div id="div_complete_contact">
<?php echo $this->getChildHtml('contacts'); ?>
</div>
