<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Create New Manufacturer')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getBackUrl()?>'" class="scalable back" type="button"><span><?php echo $this->__('Back')?></span></button>
                <button onclick="document.getElementById('edit_form').submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form id="edit_form" name="edit_form" action="<?php echo $this->getUrl('*/*/create')?>">
<div class="entry-edit">
    
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">Name</td>
                    <td class="input-ele"><input type="text" id="man_name" name="man_name" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">Main Contact</td>
                    <td class="input-ele"><input type="text" id="man_contact" name="man_contact" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">Address 1</td>
                    <td class="input-ele"><input type="text" id="man_address1" name="man_address1" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">Address 2</td>
                    <td class="input-ele"><input type="text" id="man_address2" name="man_address2" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">Zip Code</td>
                    <td class="input-ele"><input type="text" id="man_zipcode" name="man_zipcode" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">City</td>
                    <td class="input-ele"><input type="text" id="man_city" name="man_city" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">Country</td>
                    <td class="input-ele"><?php echo $this->getCountryCombo('man_country'); ?></td>
                </tr>
                <tr>
                    <td class="label">Phone</td>
                    <td class="input-ele"><input type="text" id="man_tel" name="man_tel"></td>
                </tr>
                <tr>
                    <td class="label">Fax</td>
                    <td class="input-ele"><input type="text" id="man_fax" name="man_fax"></td>
                </tr>
                <tr>
                    <td class="label">Email</td>
                    <td class="input-ele"><input type="text" id="man_email" name="man_email" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">Website</td>
                    <td class="input-ele"><input type="text" id="man_website" name="man_website" style="width:400px;"></td>
                </tr>
                <tr>
                    <td class="label">Comments</td>
                    <td class="input-ele"><textarea id="man_comments" name="man_comments" cols="100" rows="5"></textarea></td>
                </tr>
            </table>
        </fieldset>
</div>
<script type="text/javascript">
    var editForm = new varienForm('new_form');
</script>

</form>

</div>