<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Create Carrier Template')?></h3></td>
            <td align="right">
                <button onclick="document.getElementById('edit_form').submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form method="POST" id="edit_form" action="<?php echo $this->getUrl('*/*/CreateTemplate')?>">
<input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
<div class="entry-edit">
    
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">Name</td>
                    <td class="input-ele"><input type="text" id="ct_name" name="ct_name" style="width:400px;"></td>
                </tr>
            </table>
        </fieldset>
</div>

</form>

</div>

<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Import Carrier Template')?></h3></td>
            <td align="right">
                <button onclick="document.getElementById('edit_form2').submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form method="POST" enctype="multipart/form-data" id="edit_form2" action="<?php echo $this->getUrl('*/*/ImportTemplate')?>">
<input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
<div class="entry-edit">
    
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">File</td>
                    <td class="input-ele"><input type="file" name="file"></td>
                </tr>
            </table>
        </fieldset>
</div>

</form>

</div>