<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Products List')?></h3></td>
            <td align="right">
            	<i><a href="<?php echo $this->getUrl('Purchase/Misc/IdentifyErrors') ?>"><?php echo $this->__('Check for stock errors'); ?></a></i>
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getGridParentHtml() ?>

</div>