<script>

//************************************************************************************************************
function AddStockMovement()
{
	//Save en ajax
	var url = '';
	url = '<?php echo $this->getUrl('Purchase/StockMovement/Add'); ?>';
	
    var request = new Ajax.Request(
        url,
        {
            method: 'get',
            onSuccess: function onSuccess(transport)
		        			{
		        				elementValues = eval('(' + transport.responseText + ')');
		        				if (elementValues['error'] == true)
		        				{
		        					alert(elementValues['message']);
		        				}
		        				else
		        				{
			        				//Rafraichit la page
									RefreshStocksMovement();
		        				}
		        			},
			onFailure: function onFailure(transport)
		        			{
		        				//Rafraichit la page
								alert('error');
		        			},
            parameters: Form.serialize(document.getElementById('form_add_sm'))
        }
    );
    
}

//************************************************************************************************************
//Rafraichit la liste des contacts sans recharger toute la page
function RefreshStocksMovement()
{
	//definit l'url
	var url = '';
	url = '<?php echo $this->getUrl('Purchase/StockMovement/getProductStockMovement', array('product_id', $this->getProductId())); ?>';
	
	//affiche l'url dans le cadre
	var updater = new Ajax.Updater('div_stock_movement', url, {method: 'get'});
}

//*****************************************************************************************************************
//Suppression des movements de stock
function DeleteStockMovement(sm_id)
{
	if (confirm('<?php echo $this->__('Are you sure ?'); ?>'))
	{
		//Supprime le mouvement
		var url = '';
		url = '<?php echo $this->getUrl('Purchase/StockMovement/Delete', array('sm_id' => 'XXX')); ?>';
		url = url.replace('sm_id', sm_id);
		
	    var request = new Ajax.Request(
	        url,
	        {
	            method: 'get',
	            onSuccess: function onSuccess(transport)
			        			{
			        				//Rafraichit la page
									RefreshStocksMovement();
			        			},
				onFailure: function onFailure(transport)
			        			{
			        				//Rafraichit la page
									alert('error');
			        			}
	        }
	    );

	}
}

</script>


<div id="div_stock_movement">
	
	<form id="form_add_sm" name="form_add_sm">
	<input type="hidden" id="sm_product_id" name="sm_product_id" value="<?php echo $this->getProductId(); ?>">

	<div class="grid">
		<table cellspacing="0" class="data" width="100%" cellspacing="0">
        	<thead>
                <tr class="headings">
					<th class="a-center">Date</th>
					<th class="a-center">Type</th>
					<th class="a-center"><?php echo $this->__('Qty')?></th>
					<th>Description</th>
					<th class="a-center">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$collection = $this->getCollection();
					if (sizeof($collection) == 0)
					{
						echo '<tr><td colspan="5" align="center">'.$this->__('No items').'</td></tr>';
					}
					foreach ($collection as $item)
					{
						?>
						<tr>
							<td class="a-center"><?php echo $item->getsm_date(); ?></td>
							<td class="a-center"><?php echo $this->__($item->getsm_type()); ?></td>
							<td class="a-center"><?php echo (int)($item->getsm_qty() * $item->getsm_coef()); ?></td>
							<td>&nbsp;<?php echo $item->getsm_description(); ?></td>
							<td align="center"><a href="javascript:DeleteStockMovement(<?php echo $item->getsm_id(); ?>);"><?php echo $this->__('Delete')?></a></td>
						</tr>
						<?php
					}
				?>
			</tbody>
        	<thead>
                <tr class="headings">
					<th class="a-center" bgcolor="#cccccc" colspan="5"><?php echo $this->__('Add Stock Movement')?></td>
				</tr>
			</thead>
			<tr>
				<td align="center">
			    	<input size="8" type="text" id="sm_date" name="sm_date" value="<?php echo date('Y-m-d'); ?>">
			    	<img src="<?php echo $this->getSkinUrl('images/purchase/grid-cal.gif') ?>" class="v-middle" id="img_sm_date" />
			        <script type="text/javascript">
			            Calendar.setup({
			                inputField : 'sm_date',
			                ifFormat : '%Y-%m-%e',
			                button : 'img_sm_date',
			                align : 'Bl',
			                singleClick : true
			            });
			        </script>	
				</td>
				<td align="center">
					<?php echo $this->GetTypeCombo('sm_type'); ?>
				</td>
				<td align="center">
					<input type="text" name="sm_qty" id="sm_qty" size="3">
				</td>
				<td align="center">
					<input type="text" name="sm_description" id="sm_description" size="40">
				</td>
				<td align="center">
					<input type="button" value="<?php echo $this->__('Add')?>" onclick="AddStockMovement();">
				</td>
			</tr>
			</table>
		</div>
	</form>

</div>
