<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Create New Supplier')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getBackUrl()?>'" class="scalable back" type="button"><span><?php echo $this->__('Back')?></span></button>
                <button onclick="document.getElementById('edit_form').submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form id="edit_form" action="<?php echo $this->getUrl('*/*/Create')?>">
<div class="entry-edit">
    
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">Name</td>
                    <td class="input-ele"><input type="text" id="sup_name" name="sup_name" style="width:400px;"></td>
                </tr>
            </table>
        </fieldset>
</div>

</form>

<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>

</div>