<script>

//*********************************************************************************************************
//Lie un fabricant au produit
function linkManufacturer()
{

	//recupere les infos
	var manufacturer_id = '';
	var product_id = '';
	manufacturer_id = document.getElementById('manufacturer').value;
	product_id = <?php echo $this->getProductId(); ?>;
	
	//définit l'url
	var url = '';
	url = '<?php echo $this->getUrl('Purchase/Products/LinkManufacturer', array('product_id' => 'XXX', 'manufacturer_id' => 'YYY')); ?>';
	url = url.replace('XXX', product_id);
	url = url.replace('YYY', manufacturer_id);
	
	//Appel l'url en ajax
	var request = new Ajax.Request(url,
	    {
	        method:'get',
	        onSuccess: function onSuccess(transport)
	        			{
	        				RefreshAssociatedManufacturers()
	        			},
	        onFailure: function onAddressFailure() {alert('error');}
	    }
    );
}

//************************************************************************************************************
//charge une association avec un manufacturer pour l'éditer
function loadManufacturer(Id)
{
	//définit l'url
	var url = '';
	url = '<?php echo $this->getUrl('Purchase/Products/GetManufacturerInformation', array('ppm_id' => 'XXX')) ?>';
	url = url.replace('XXX', Id);

	//Appel en ajax
	var request = new Ajax.Request(url,
	    {
	        method:'get',
	        onSuccess: function onSuccess(transport)
	        			{
	        				//recupere les données
	        				elementValues = eval('(' + transport.responseText + ')');
	        				
	        				//Affiche les données dans les champs
	        				document.getElementById('ppm_reference').value = elementValues['ppm_reference'];
	        				document.getElementById('ppm_comments').value = elementValues['ppm_comments'];
	        				document.getElementById('ppm_id').value = elementValues['ppm_id'];
	        				
	        				//Affiche le calque d'edition
	        				document.getElementById('div_manufacturer_edit').style.display = 'block';
	        			},
	        onFailure: function onAddressFailure() 
	        			{
							document.getElementById('div_manufacturer_edit').style.display = 'none';
	        				alert('error');
	        			}
	    }
    );
	
}


//************************************************************************************************************
//Rafraichit la liste des manifacturers associés
function RefreshAssociatedManufacturers()
{
	var url;
	url = '<?php echo $this->getUrl('*/*/*', array('product_id' => $this->getProductId(), 'tab' => 'tab_manufacturers')) ?>';
	document.location.href = url;
}

//************************************************************************************************************
//Supprime l'association avec un manufacturer
function removeManufacturer(id)
{
	if (confirm('<?php echo $this->__('Are you sure ?'); ?>'))
	{
		//définit l'url
		var url = '';
		url = '<?php echo $this->getUrl('Purchase/Products/DeleteAssociatedManufacturer', array('ppm_id' => 'XXX')); ?>';
		url = url.replace('XXX', id);
		
		//Appel en ajax
		var request = new Ajax.Request(url,
		    {
		        method:'get',
		        onSuccess: function onSuccess(transport)
		        			{
		        				//Rafraichit la page
								RefreshAssociatedManufacturers();
		        			},
		        onFailure: function onFailure() 
		        			{
		        				alert('error');
		        			}
		    }
	    );
	}
}

//************************************************************************************************************
//sauvegarde les modifs sur le manufacturer
function SaveAssociatedManufacturer()
{
	//Save en ajax
	var url = '';
	url = '<?php echo $this->getUrl('Purchase/Products/SaveAssociatedManufacturer'); ?>';
	
    var request = new Ajax.Request(
        url,
        {
            method: 'post',
            onSuccess: function onSuccess(transport)
		        			{
		        				//Rafraichit la page
								RefreshAssociatedManufacturers();
		        			},
			onFailure: function onFailure(transport)
		        			{
		        				//Rafraichit la page
								alert('error');
		        			},
            parameters: Form.serialize(document.getElementById('form_associated_manufacturers'))
        }
    );
}

</script>

        <div class="grid">
			<table cellspacing="0" class="data" width="100%">
				<thead>
					<tr class="headings">
						<th><?php echo $this->__('Name')?></th>
						<th><?php echo $this->__('Reference')?></th>
						<th class="a-center"><?php echo $this->__('Action')?></th>
					</tr>
				</thead>
				<tbody>
					<?php
						$Manufacturers = $this->getManufacturers();
						foreach ($Manufacturers as $Manufacturer)
						{
							echo '<tr>';
							echo '<td><a href="'.$this->getUrl('Purchase/Manufacturers/Edit').'man_id/'.$Manufacturer->getppm_manufacturer_num().'">'.$Manufacturer->getman_name().'</a></td>';
							echo '<td>&nbsp;'.$Manufacturer->getppm_reference().'</td>';
							echo '<td class="a-center"><a href="javascript:loadManufacturer('.$Manufacturer->getppm_id().');">'.$this->__('Edit').'</a> - <a href="javascript:removeManufacturer('.$Manufacturer->getppm_id().')">'.$this->__('Delete').'</a></td>';
							echo '</tr>';
						}
					?>
				</tbody>
				<thead>
					<tr class="headings">
						<th class="a-center" colspan="3"><?php echo $this->__('Add Manufacturer')?></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class="a-center" colspan="3"><?php echo $this->getNonLinkedManufacturersAsCombo(); ?> <input type="button" value="<?php echo $this->__('Add')?>" onclick="linkManufacturer();"></td>
					</tr>
				</tbody>
			</table>
        </div>
        
        <div id="div_manufacturer_edit" style="display: none">
			<fieldset>
				<form id="form_associated_manufacturers" name="form_associated_manufacturers">
				<input type="hidden" id="ppm_id" name="ppm_id" value="">
				<table border="0" width="100%">
				<tr>
					<td><?php echo $this->__('Manufacturer Reference')?></td>
					<td><input type="text" id="ppm_reference" name="ppm_reference"></td>
				</tr>
				<tr>
					<td><?php echo $this->__('Comments')?></td>
					<td><textarea id="ppm_comments" name="ppm_comments" cols="50" rows="3"></textarea></td>
				</tr>
				<tr>
					<td><?php echo $this->__('Save')?></td>
					<td><input type="button" value="<?php echo $this->__('Save')?>" onclick="SaveAssociatedManufacturer();"></td>
				</tr>
				</table>
				</form>
			</fieldset>
		</div>