<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Edit Contact')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getBackUrl()?>'" class="scalable back" type="button"><span><?php echo $this->__('Back')?></span></button>
                <button onclick="document.getElementById('edit_form').submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form id="edit_form" name="edit_form" action="<?php echo $this->getUrl('*/*/Save')?>">
<input type="hidden" id="pc_num" name="pc_num" value="<?php echo $this->getContact()->getId(); ?>">
<div class="entry-edit">
    
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">Id</td>
                    <td class="input-ele"><?php echo $this->getContact()->getId(); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Entity')?></td>
                    <td class="input-ele"><?php echo $this->getContact()->getContactEntityAsText(); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Lastname')?></td>
                    <td class="input-ele"><input type="text" id="pc_lastname" name="pc_lastname" style="width:400px;" value="<?php echo $this->getContact()->getpc_lastname(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Firstname')?></td>
                    <td class="input-ele"><input type="text" id="pc_firstname" name="pc_firstname" style="width:400px;" value="<?php echo $this->getContact()->getpc_firstname(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Function')?></td>
                    <td class="input-ele"><input type="text" id="pc_function" name="pc_function" style="width:400px;" value="<?php echo $this->getContact()->getpc_function(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Phone')?></td>
                    <td class="input-ele"><input type="text" id="pc_phone" name="pc_phone" style="width:400px;" value="<?php echo $this->getContact()->getpc_phone(); ?>"></td>
                </tr>
                <tr>
                    <td class="label">Fax</td>
                    <td class="input-ele"><input type="text" id="pc_fax" name="pc_fax" style="width:400px;" value="<?php echo $this->getContact()->getpc_fax(); ?>"></td>
                </tr>
                <tr>
                    <td class="label">Mobile</td>
                    <td class="input-ele"><input type="text" id="pc_mobile" name="pc_mobile" style="width:400px;" value="<?php echo $this->getContact()->getpc_mobile(); ?>"></td>
                </tr>
                <tr>
                    <td class="label">Email</td>
                    <td class="input-ele"><input type="text" id="pc_email" name="pc_email" style="width:400px;" value="<?php echo $this->getContact()->getpc_email(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Country')?></td>
                    <td class="input-ele"><?php echo $this->getCountryCombo('pc_country', $this->getContact()->getpc_country()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Comments')?></td>
                    <td class="input-ele"><textarea id="pc_comments" name="pc_comments" cols="100" rows="4"><?php echo $this->getContact()->getpc_comments(); ?></textarea></td>
                </tr>
            </table>
        </fieldset>
</div>


</div>

</form>