<script>

//************************************************************************************************************************************************
//Suppression d'un manufacturer associé
function deleteAssociatedManufacturer(id)
{
	if (confirm('<?php echo $this->__('Are you sure ?'); ?>'))
	{
		//définit l'url
		var url = '';
		url = '<?php echo $this->getUrl('Purchase/Suppliers/DeleteAssociatedManufacturer', array('pms_num' => 'XXX')); ?>';
		url = url.replace('XXX', id);
		
		//Appel en ajax
		var request = new Ajax.Request(url,
		    {
		        method:'get',
		        onSuccess: function onSuccess(transport)
		        			{
		        				//Rafraichit la page
								RefreshList();
		        			},
		        onFailure: function onFailure() 
		        			{
		        				alert('error');
		        			}
		    }
	    );
	}
}

//************************************************************************************************************
//Rafraichit la liste sans recharger toute la page
function RefreshList()
{
	//definit l'url
	var url = '';
	url = '<?php echo $this->getUrl('Purchase/Suppliers/Edit', array('sup_id' => $this->getSupplierId(), 'tab' => 'tab_manufacturers')); ?>';

	//affiche l'url dans le cadre
	//var updater = new Ajax.Updater('div_complete_associatedmanufacturers', url, {method: 'get'});
	document.location.href = url;
}

//************************************************************************************************************
//sauvegarde les modifs sur les manufacturers associés
function SaveAssociatedManufacturers()
{
	//Save en ajax
	var url = '';
	url = '<?php echo $this->getUrl('Purchase/Suppliers/SaveManufacturersSuppliers'); ?>';
	
    var request = new Ajax.Request(
        url,
        {
            method: 'post',
            onSuccess: function onSuccess(transport)
		        			{
		        				//Rafraichit la page
								RefreshList();
		        			},
			onFailure: function onFailure(transport)
		        			{
		        				//Rafraichit la page
								alert('error');
		        			},
            parameters: Form.serialize(document.getElementById('form_associated_manufacturers'))
        }
    );
}

</script>

<div class="entry-edit" id="div_contact_list" name="div_contact_list">
    
        <div class="grid">
				<table cellspacing="0" class="data" width="100%">
		        	<thead>
						<tr class="headings">
							<th><?php echo$this->__('Manufacturers')?></th>
							<th class="a-center"><?php echo$this->__('Official')?></th>
							<th class="a-center"><?php echo$this->__('Price')?></th>
							<th class="a-center"><?php echo$this->__('Range')?></th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						<?php
							//Affiche la liste
							$collection = $this->getManufacturers();
							foreach ($collection as $item)
							{
								echo '<tr>';
								echo '<td>'.$item->getman_name().'</td>';
								$checked = '';
								if ($item->getpms_official() == '1')
									$checked = ' checked ';
								echo '<td class="a-center"><input type="checkbox" id="pms_official_'.$item->getpms_num().'" name="pms_official_'.$item->getpms_num().'" value="1" '.$checked.'></td>';
								echo '<td class="a-center">'.$this->getPricePositionAsCombo('pms_price_position_'.$item->getpms_num(), $item->getpms_price_position()).'</td>';
								echo '<td class="a-center"><input type="text" id="pms_gamme_'.$item->getpms_num().'" name="pms_gamme_'.$item->getpms_num().'" value="'.$item->getpms_gamme().'"></td>';
								echo '<td class="a-center">';
								echo '<a href="javascript:deleteAssociatedManufacturer('.$item->getpms_num().');">'.$this->__('Delete').'</a></td>';
								echo '</tr>';
							}
						?>
					</tbody>
		        	<thead>
						<tr class="headings">
							<th class="a-center" colspan="5"><?php echo $this->__('Add Manufacturer'); ?></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="a-center"><?php echo $this->getOtherManufacturesAsCombo('add_pms_manufacturer_id'); ?></td>
							<td class="a-center"><input type="checkbox" value="1" id="add_pms_official" name="add_pms_official"></td>
							<td class="a-center"><?php echo $this->getPricePositionAsCombo('add_pms_price_position', ''); ?></td>
							<td class="a-center"><input type="text" value="" id="add_pms_gamme" name="add_pms_gamme"></td>
							<td class="a-center"><a href="javascript:document.getElementById('edit_form').submit()">Save</a></td>
						</tr>
					</tbody>
				</table>
	    </div>
</div>
