<div class="entry-edit">

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Background Tasks')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getClearAllTasksUrl()?>'" class="scalable " type="button"><span><?php echo $this->__('Clear all Tasks')?></span></button>
                <button onclick="document.location.href='<?php echo $this->getClearGroupTasksUrl()?>'" class="scalable " type="button"><span><?php echo $this->__('Clear group Tasks')?></span></button>
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getGridParentHtml() ?>

</div>